# Generated by Django 5.0 on 2023-12-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='услуга')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('contraindications', models.TextField(blank=True, null=True, verbose_name='противопоказания')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
    ]
